shady-search:
  maxSectors: 144
  ui:
    height: 1080
    title: X4 Black Marketeer Finder
    width: 1400

spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    password: x4
    url: jdbc:hsqldb:res:./db/x4db
    username: x4
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.HSQLDialect
  main:
    web-application-type: none
